### ISSUE TITLE
extraClasspath() method on WebAppContext dont support dir path

### ISSUE THREAD

**Issue by dn2k-dev** [jetty-project/jetty-documentation#43]
Hi,

I am trying to load extra libs using extraClasspath() from a dir path but jars are not loaded.
if I specify the list of jars one by one it works well.
I checked that in Jetty 8 and Jetty 9
I need it to work for Jetty 8 mostly.

my configuration:

<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">

    <Set name="contextPath">/war</Set>
    <Set name="war"><Env name="SERVER" default="."/>/app/webapps/war.war</Set>
    <Set name="extraClasspath"><Env name="SERVER" default="."/>/extralibs</Set>
    <Call name="setInitParameter">
        <Arg>org.eclipse.jetty.servlet.Default.dirAllowed</Arg>
        <Arg>false</Arg>
    </Call>
</Configure>

**Comment by joakime** [comment]
Exists as bug https://bugs.eclipse.org/438482
