### ISSUE TITLE
Build failed, 

### ISSUE THREAD

**Issue by darkjune** [jetty-project/jetty-documentation#46]
Do maven install, met below error, I'm not familiar with docbkx, anyone can fix this?
Line 329 may have some problem? <xsl:variable name="newText" select="jfetch:fetch($filename,$methodname)"/>

[INFO] --- docbkx-maven-plugin:2.0.14:generate-html (html) @ jetty-documentation
 ---
[INFO] Executing tasks
[INFO] Executed tasks
[INFO] Processing input file: jetty.xml
[INFO] Dumping to E:\workspace\my-jetty-documentation\target\docbkx\generated\(g
en)jetty.xml
[INFO] Applying customization parameters
[INFO] Chunking output.
Not Cached:
      http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/plain/example
s/embedded/src/main/java/org/eclipse/jetty/embedded/ExampleServer.java
Error at xsl:variable on line 329 of file:/E:/workspace/my-jetty-documentation/s
rc/docbkx-stylesheet/html/docbook.xsl:
  Exception in extension function java.io.IOException: The filename, directory n
ame, or volume label syntax is incorrect

**Comment by joakime** [comment]
The jetty-documentation build is not supported on windows (the paths are too deep)
