### ISSUE TITLE
Jetty-8 METHOD PUT DELETE enable ?

### ISSUE THREAD

**Issue by edisonch** [jetty-project/jetty-documentation#49]
Dear All,

In the documentation, there is no mention about how to enable method PUT / DELETE in jetty 8.xx / 9.xx ? by default jetty only enable method GET / POST. any explanation or documentation on how to enable those two methods?

**Comment by joakime** [comment]
PUT and DELETE are not disabled by Jetty, in any version of Jetty.

Your application, on the other hand, can disable PUT and DELETE, simply by choosing to not implement it, or by using servlet security constraints.
