### ISSUE TITLE
Example batch file doesn't quote directories with spaces in them

### ISSUE THREAD

**Issue by kristian-meyer** [jetty-project/jetty-documentation#60]
On the following page, 

http://www.eclipse.org/jetty/documentation/9.1.2.v20140210/startup-windows-service.html

Setting variables to directories with spaces in them, such as the following, don't quote the directory, this won't work in a batch file.:

@REM Path to Java Installation
set JAVA_HOME=C:\Program Files\Java\jdk1.7.0_45

it should be:

set JAVA_HOME="C:\Program Files\Java\jdk1.7.0_45"

I'm assuming this example was tested, but the quotes got eaten by something.

**Comment by joakime** [comment]
Closing as fixed
