### ISSUE TITLE
Document that classpath is built from pom dependencies under jetty:run/start

### ISSUE THREAD

**Issue by azzoti** [jetty-project/jetty-documentation#78]
From experience and some guesswork, I believe that jetty:run builds the classpath to run the server from a number of sources, but in particular by analysing the pom dependencies in which the maven jetty plugin is configured (at least I think that it is how it works). It then sets the classpath by referencing the relevant jars in the local maven repository (again I think that it is how it works). This is almost undocumented (and very useful!). It is tersely alluded to in the  "Scanner Matrix" section. Something a little more explicit would be great, even a one line liner, perhaps under the jetty:run/start section?. I'd do it myself but I am not sure enough about the details.

**Comment by joakime** [comment]
Seems that most of what you are asking about is standard maven environment and plugin behavior with regards to classpath.

Why would we duplicate what is documented at maven?

**Comment by azzoti** [comment]
Hi Joakim,

In:
jetty:run

The run goal runs on a webapp that does not have to be built into a WAR.
Instead, Jetty deploys the webapp from its sources. It looks for the
constituent parts of a webapp in the Maven default project locations,
although you can override these in the plugin configuration. For example,
by default it looks for:

   -

   resources in ${project.basedir}/src/main/webapp
   -

   classes in ${project.build.outputDirectory}
   -

   web.xml in ${project.basedir}/src/main/webapp/WEB-INF/


I'd add something like:

   - jars from standard maven dependencies from pom.xml (that would
   normally be in WEB-INF/lib in a packaged war file)


That would have saved me some head scratching and given that resources and
classes are explicity mentioned even though this duplicates what is
documented at maven, I can't see the harm.

Thanks

Tim

On 24 June 2015 at 00:35, Joakim Erdfelt <notifications@github.com> wrote:

> Seems that most of what you are asking about is standard maven environment
> and plugin behavior with regards to classpath.
>
> Why would we duplicate what is documented at maven?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jetty-project/jetty-documentation/issues/78#issuecomment-114674526>
> .
>



-- 
-o-

**Comment by joakime** [comment]
Added note.
