### ISSUE TITLE
version in maven plugin doc is wrong

### ISSUE THREAD

**Issue by lacivert** [jetty-project/jetty-documentation#82]
Here I see the version of maven plugin: 9.3.1-SNAPSHOT

http://www.eclipse.org/jetty/documentation/current/jetty-maven-plugin.html

But there is not version here:

http://mvnrepository.com/artifact/org.eclipse.jetty/jetty-maven-plugin

So, version 9.3.1-SNAPSHOT is wrong. It should be one of the real versions

**Comment by joakime** [comment]
Corrected
