### ISSUE TITLE
OT: jetty docs as epub

### ISSUE THREAD

**Issue by edoardoc** [jetty-project/jetty-documentation#85]
Hi,

is there a way to have jetty doc in a one page html file?
purpose: converting it to an ereader format

thanks

**Comment by joakime** [comment]
Our documentation is in docbook format.
Got any pointers on how to go from docbook -> epub?
There's got to be a way.

**Comment by jmcc0nn3ll** [comment]
you can do it now into epub with a new execution in the pom.xml file....it renders a bit funky for tables and examples so I didn't put much effort into it beyond trying it out

there are also options to render into a single html as well through the pom.xml configuration

**Comment by edoardoc** [comment]
I was thinking of doing it with https://dotepub.com but I will try maven target also

thanks for the tips
