### ISSUE TITLE
openssl -b parameter produces error, 

### ISSUE THREAD

**Issue by kristian-meyer** [jetty-project/jetty-documentation#91]
On the page

http://www.eclipse.org/jetty/documentation/current/configuring-ssl.html

The line:

    openssl req -new -x509 -b2048 -sha256 -key jetty.key -out jetty.crt

Produces the following error in my version of openssl:  `unknown option -b2048`

I used this line instead, which seemed to work, although I didn't test the resulting file:

    openssl req -new -x509 -newkey rsa:2048 -sha256 -key jetty.key -out jetty.crt

My version of openssl is `openssl (1.0.1-4ubuntu5.33) `, which is fairly recent, from Dec 2015.

I also had to add https as a method, to the default jetty config, with the following command,  for https to work, otherwise I got a connection refused error.  This isn't mentioned in the docs, should it be added?

     java -jar $JETTY_HOME/start.jar --add-to-startd=https

Also on that page the following links are dead:

    http://en.tldp.org/HOWTO/SSL%20Certificates%20HOWTO
    https://www.openssl.org/docs/HOWTO/

**Comment by joakime** [comment]
Fixed.  Thanks!

**Comment by kristian-meyer** [comment]
Thanks for your work.  I missed this sentence, which also refers to the old -b parameter:

    For the paranoid ones add -b4096 to get a 4069bits long key.

This probably should now say:

    For the paranoid ones add rsa:4096 to get a 4096-bit key.
