### ISSUE TITLE
Document "What Version Do I Use?" shows wrong java version for jetty 9.3

### ISSUE THREAD

**Issue by jmquint** [jetty-project/jetty-documentation#92]
https://www.eclipse.org/jetty/documentation/9.2.7.v20150116/what-jetty-version.html

9.3 says JVM 1.7 when 1.8 is required

**Comment by joakime** [comment]
We don't update old (archived) documentation.

The current version is correct.
https://www.eclipse.org/jetty/documentation/current/what-jetty-version.html
